import type { StudentResponse } from "../model/student_types";

export async function fetchStudents(): Promise<StudentResponse[]> {
  return Promise.resolve([
    {
      id: "1",
      name: "Lola",
      phone: "0612234353",
      subscriptionType: "freemium",
      planType: "annual",
      device: "Ordinateur / iOS",
      gender: "Fille",
      registrationDate: "08/07/2024",
      level: "CM1",
    },
    {
      id: "2",
      name: "Salma",
      phone: "0612234678",
      subscriptionType: "premium",
      planType: "monthly",
      device: "Mobile / Android",
      gender: "Fille",
      registrationDate: "12/12/2022",
      level: "CP",
    },
    {
      id: "3",
      name: "Imane",
      phone: "0612234540",
      subscriptionType: "essai-gratuit",
      planType: "trimestriel",
      device: "Tablet / MacOS",
      gender: "Fille",
      registrationDate: "11/02/2023",
      level: "CM1",
    },
    {
      id: "4",
      name: "Aya",
      phone: "0612234456",
      subscriptionType: "pro",
      planType: "semestriel",
      device: "Desktop / Web",
      gender: "Fille",
      registrationDate: "22/04/2023",
      level: "CM2",
    },
    {
      id: "5",
      name: "Sara",
      phone: "0612234369",
      subscriptionType: "freemium",
      planType: "annual",
      device: "Desktop / iOS",
      gender: "Fille",
      registrationDate: "08/07/2024",
      level: "CM1",
    },
    {
      id: "6",
      name: "Hiba",
      phone: "0612234222",
      subscriptionType: "premium",
      planType: "annual",
      device: "Mobile / Windows",
      gender: "Fille",
      registrationDate: "12/12/2022",
      level: "CP",
    },
    {
      id: "7",
      name: "Nora",
      phone: "0612234111",
      subscriptionType: "essai-gratuit",
      planType: "monthly",
      device: "Mobile / MacOS",
      gender: "Fille",
      registrationDate: "11/02/2023",
      level: "CM1",
    },
    {
      id: "8",
      name: "Lamia",
      phone: "0612234778",
      subscriptionType: "essai-gratuit",
      planType: "trimestriel",
      device: "Tablet / MacOS",
      gender: "Fille",
      registrationDate: "22/04/2023",
      level: "CM2",
    },
    {
      id: "9",
      name: "Zineb",
      phone: "0612234988",
      subscriptionType: "pro",
      planType: "trimestriel",
      device: "Desktop / Web",
      gender: "Fille",
      registrationDate: "22/04/2023",
      level: "CP",
    },
    {
      id: "10",
      name: "Salma",
      phone: "0612234411",
      subscriptionType: "freemium",
      planType: "annual",
      device: "Desktop / iOS",
      gender: "Fille",
      registrationDate: "08/07/2024",
      level: "CM1",
    },
    {
      id: "11",
      name: "Karim",
      phone: "0612234512",
      subscriptionType: "premium",
      planType: "monthly",
      device: "Mobile / Android",
      gender: "Garçon",
      registrationDate: "01/01/2023",
      level: "CE1",
    },
    {
      id: "12",
      name: "Youssef",
      phone: "0612234623",
      subscriptionType: "freemium",
      planType: "annual",
      device: "Ordinateur / iOS",
      gender: "Garçon",
      registrationDate: "15/03/2023",
      level: "CE2",
    },
    {
      id: "13",
      name: "Mehdi",
      phone: "0612234734",
      subscriptionType: "pro",
      planType: "trimestriel",
      device: "Desktop / Web",
      gender: "Garçon",
      registrationDate: "20/05/2023",
      level: "CM2",
    },
    {
      id: "14",
      name: "Adam",
      phone: "0612234845",
      subscriptionType: "essai-gratuit",
      planType: "semestriel",
      device: "Tablet / MacOS",
      gender: "Garçon",
      registrationDate: "10/08/2023",
      level: "CM1",
    },
    {
      id: "15",
      name: "Omar",
      phone: "0612234956",
      subscriptionType: "premium",
      planType: "monthly",
      device: "Mobile / Windows",
      gender: "Garçon",
      registrationDate: "05/09/2023",
      level: "CP",
    },
    {
      id: "16",
      name: "Rania",
      phone: "0612234167",
      subscriptionType: "freemium",
      planType: "annual",
      device: "Desktop / iOS",
      gender: "Fille",
      registrationDate: "01/02/2024",
      level: "CE1",
    },
    {
      id: "17",
      name: "Dounia",
      phone: "0612234278",
      subscriptionType: "pro",
      planType: "monthly",
      device: "Mobile / Android",
      gender: "Fille",
      registrationDate: "14/03/2024",
      level: "CE2",
    },
    {
      id: "18",
      name: "Fatima",
      phone: "0612234389",
      subscriptionType: "premium",
      planType: "trimestriel",
      device: "Tablet / MacOS",
      gender: "Fille",
      registrationDate: "25/04/2024",
      level: "CM1",
    },
    {
      id: "19",
      name: "Nadia",
      phone: "0612234490",
      subscriptionType: "freemium",
      planType: "semestriel",
      device: "Desktop / Web",
      gender: "Fille",
      registrationDate: "30/05/2024",
      level: "CM2",
    },
    {
      id: "20",
      name: "Rim",
      phone: "0612234501",
      subscriptionType: "essai-gratuit",
      planType: "annual",
      device: "Ordinateur / iOS",
      gender: "Fille",
      registrationDate: "18/06/2024",
      level: "CP",
    },
    {
      id: "21",
      name: "Hamza",
      phone: "0612234612",
      subscriptionType: "premium",
      planType: "monthly",
      device: "Mobile / Android",
      gender: "Garçon",
      registrationDate: "02/01/2024",
      level: "CE1",
    },
    {
      id: "22",
      name: "Bilal",
      phone: "0612234723",
      subscriptionType: "freemium",
      planType: "trimestriel",
      device: "Desktop / Web",
      gender: "Garçon",
      registrationDate: "11/02/2024",
      level: "CE2",
    },
    {
      id: "23",
      name: "Tarik",
      phone: "0612234834",
      subscriptionType: "pro",
      planType: "annual",
      device: "Tablet / MacOS",
      gender: "Garçon",
      registrationDate: "22/03/2024",
      level: "CM1",
    },
    {
      id: "24",
      name: "Saad",
      phone: "0612234945",
      subscriptionType: "premium",
      planType: "semestriel",
      device: "Mobile / Windows",
      gender: "Garçon",
      registrationDate: "05/04/2024",
      level: "CM2",
    },
    {
      id: "25",
      name: "Ilyas",
      phone: "0612234056",
      subscriptionType: "essai-gratuit",
      planType: "monthly",
      device: "Desktop / iOS",
      gender: "Garçon",
      registrationDate: "19/05/2024",
      level: "CP",
    },
    {
      id: "26",
      name: "Ghita",
      phone: "0612234167",
      subscriptionType: "freemium",
      planType: "annual",
      device: "Ordinateur / iOS",
      gender: "Fille",
      registrationDate: "07/06/2024",
      level: "CE1",
    },
    {
      id: "27",
      name: "Hajar",
      phone: "0612234278",
      subscriptionType: "pro",
      planType: "trimestriel",
      device: "Mobile / Android",
      gender: "Fille",
      registrationDate: "13/07/2024",
      level: "CE2",
    },
    {
      id: "28",
      name: "Widad",
      phone: "0612234389",
      subscriptionType: "premium",
      planType: "monthly",
      device: "Tablet / MacOS",
      gender: "Fille",
      registrationDate: "21/08/2024",
      level: "CM1",
    },
    {
      id: "29",
      name: "Sanaa",
      phone: "0612234490",
      subscriptionType: "freemium",
      planType: "semestriel",
      device: "Desktop / Web",
      gender: "Fille",
      registrationDate: "09/09/2024",
      level: "CM2",
    },
    {
      id: "30",
      name: "Layla",
      phone: "0612234501",
      subscriptionType: "essai-gratuit",
      planType: "annual",
      device: "Ordinateur / iOS",
      gender: "Fille",
      registrationDate: "30/10/2024",
      level: "CP",
    },
  ]);
}
